- pkg:composer/jakubandrysek/chart@3.0.0
- pkg:composer/jakubandrysek/chart@3.2.0
- pkg:composer/jakubandrysek/chart@v1.0.0
- pkg:composer/jakubandrysek/chart@v2.0.0
- pkg:composer/jakubandrysek/chart@v3.1.0
