- pkg:composer/nouvu/config@4.2
- pkg:composer/nouvu/config@v3.1
- pkg:composer/nouvu/config@v3.1.1
- pkg:composer/nouvu/config@v3.1.2
- pkg:composer/nouvu/config@v4.0.0
- pkg:composer/nouvu/config@v4.1.0
- pkg:composer/nouvu/config@v4.2.1
- pkg:composer/nouvu/config@v4.2.2
