- pkg:composer/vakata/config@1.0.0
- pkg:composer/vakata/config@1.1.0
- pkg:composer/vakata/config@1.1.1
- pkg:composer/vakata/config@1.1.2
- pkg:composer/vakata/config@1.1.3
- pkg:composer/vakata/config@1.1.4
- pkg:composer/vakata/config@1.1.5
- pkg:composer/vakata/config@2.0.0
- pkg:composer/vakata/config@2.0.1
- pkg:composer/vakata/config@2.0.2
- pkg:composer/vakata/config@2.1.0
- pkg:composer/vakata/config@2.1.1
- pkg:composer/vakata/config@2.2.0
- pkg:composer/vakata/config@2.2.1
