- pkg:composer/k8s/client@1.0.0
- pkg:composer/k8s/client@1.1.0
- pkg:composer/k8s/client@1.2.0
- pkg:composer/k8s/client@1.3.0
- pkg:composer/k8s/client@1.3.1
- pkg:composer/k8s/client@1.4.0
- pkg:composer/k8s/client@1.4.1
- pkg:composer/k8s/client@1.5.0
- pkg:composer/k8s/client@1.5.1
- pkg:composer/k8s/client@1.6.0
- pkg:composer/k8s/client@1.7.0
