- pkg:composer/feidu/docker@18.06.07
- pkg:composer/feidu/docker@18.06.08
- pkg:composer/feidu/docker@18.06.09
- pkg:composer/feidu/docker@18.06.10
- pkg:composer/feidu/docker@18.06.11
- pkg:composer/feidu/docker@18.06.12
- pkg:composer/feidu/docker@v1.0.0
